In [1]:
import numpy as np

In [2]:
x=np.array([[1,2],[3,4],[5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
y=np.array([[1, 0, 1], [0, 1, 0], [1, 1, 0]])
y

array([[1, 0, 1],
       [0, 1, 0],
       [1, 1, 0]])

Manual computation of 
$$
z[i, k] = x[i, y[i, k]]
$$

In [22]:
z_manual = np.empty(y.shape)
for i in range(0, y.shape[0]):
    for k in range(0, y.shape[1]):
        z_manual[i, k] = x[i, y[i, k]]
z_manual

array([[2., 1., 2.],
       [3., 4., 3.],
       [6., 6., 5.]])

Construct y_onehot$[i,k, j] = 1$ if $y[i,j] == k$, 0 otherwise.

In [23]:
y_onehot = np.zeros((y.shape[0], y.shape[1], x.shape[1]))
for i in range(0, y.shape[0]):
    for j in range(0, x.shape[1]):
        for k in range(0, y.shape[1]):
            if y[i, k] == j:
                y_onehot[i, k, j] = 1
y_onehot

array([[[0., 1.],
        [1., 0.],
        [0., 1.]],

       [[1., 0.],
        [0., 1.],
        [1., 0.]],

       [[0., 1.],
        [0., 1.],
        [1., 0.]]])

In [25]:
z_einsum = np.einsum('ij, ikj->ik', x, y_onehot)
z_einsum

array([[2., 1., 2.],
       [3., 4., 3.],
       [6., 6., 5.]])

In [27]:
np.all(z_einsum==z_manual)

True